# Uncomment the next line to define a global platform for your project
# platform :ios, ’12.0’


source 'https://github.com/CocoaPods/Specs.git'
target 'trackStar' do
  platform :ios, '9.0'
#  pod 'GooglePlacePicker', '= 2.7.0'
  pod 'GooglePlaces', '= 3.1.0'
  pod 'GoogleMaps', '= 3.1.0'
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
end
